/*
 * Copyright (c) 2020 Antti Tiihala
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * boot/palette.h
 *      Header of Dancy Operating System
 */

#ifndef BOOT_PALETTE_H
#define BOOT_PALETTE_H

#define DANCY_PALETTE_0 0x00000000
#define DANCY_PALETTE_1 0x00101010
#define DANCY_PALETTE_2 0x00202020
#define DANCY_PALETTE_3 0x00303030
#define DANCY_PALETTE_4 0x00404040
#define DANCY_PALETTE_5 0x00505050
#define DANCY_PALETTE_6 0x00606060
#define DANCY_PALETTE_7 0x00707070

#define DANCY_PALETTE_8 0x00808080
#define DANCY_PALETTE_9 0x00909090
#define DANCY_PALETTE_A 0x00A0A0A0
#define DANCY_PALETTE_B 0x00B0B0B0
#define DANCY_PALETTE_C 0x00C0C0C0
#define DANCY_PALETTE_D 0x00D0D0D0
#define DANCY_PALETTE_E 0x00E0E0E0
#define DANCY_PALETTE_F 0x00F0F0F0

#endif
