# Dancy Operating System

##############################################################################

./scripts/dancy.mk:
	@mkdir "arctic/bin32"
	@mkdir "arctic/bin64"
	@mkdir "arctic/o32"
	@mkdir "arctic/o32/hello"
	@mkdir "arctic/o32/libc"
	@mkdir "arctic/o32/libc/a32"
	@mkdir "arctic/o64"
	@mkdir "arctic/o64/hello"
	@mkdir "arctic/o64/libc"
	@mkdir "arctic/o64/libc/a64"
	@mkdir "bin"
	@mkdir "efi"
	@mkdir "efi/boot"
	@mkdir "o32"
	@mkdir "o32/_boot"
	@mkdir "o32/_boot/init"
	@mkdir "o32/_boot/init/a32"
	@mkdir "o32/_boot/init/smp"
	@mkdir "o32/_common"
	@mkdir "o32/_common/a32"
	@mkdir "o32/acpica"
	@mkdir "o32/acpios"
	@mkdir "o32/acpios/a32"
	@mkdir "o32/base"
	@mkdir "o32/base/a32"
	@mkdir "o32/debug"
	@mkdir "o32/lib"
	@mkdir "o32/lib/a32"
	@mkdir "o32/misc"
	@mkdir "o32/pci"
	@mkdir "o32/ps2"
	@mkdir "o32/sched"
	@mkdir "o32/syscall"
	@mkdir "o32/syscall/a32"
	@mkdir "o32/vfs"
	@mkdir "o64"
	@mkdir "o64/_boot"
	@mkdir "o64/_boot/init"
	@mkdir "o64/_boot/init/a64"
	@mkdir "o64/_boot/init/smp"
	@mkdir "o64/_boot/uefi"
	@mkdir "o64/_boot/uefi/a64"
	@mkdir "o64/_common"
	@mkdir "o64/_common/a64"
	@mkdir "o64/acpica"
	@mkdir "o64/acpios"
	@mkdir "o64/acpios/a64"
	@mkdir "o64/base"
	@mkdir "o64/base/a64"
	@mkdir "o64/debug"
	@mkdir "o64/lib"
	@mkdir "o64/lib/a64"
	@mkdir "o64/misc"
	@mkdir "o64/pci"
	@mkdir "o64/ps2"
	@mkdir "o64/sched"
	@mkdir "o64/syscall"
	@mkdir "o64/syscall/a64"
	@mkdir "o64/vfs"
	@mkdir "release"
	@mkdir "system"
	$(DANCY_MK)
