/*
 * Copyright (c) 2018, 2019, 2021 Antti Tiihala
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * dancy/keys.h
 *      Header of Dancy Operating System
 */

#ifndef DANCY_KEYS_H
#define DANCY_KEYS_H

enum dancy_key {
	DANCY_KEY_NULL,
	DANCY_KEY_ERROR1,
	DANCY_KEY_ERROR2,
	DANCY_KEY_UNDEFINED,
	DANCY_KEY_A,
	DANCY_KEY_B,
	DANCY_KEY_C,
	DANCY_KEY_D,
	DANCY_KEY_E,
	DANCY_KEY_F,
	DANCY_KEY_G,
	DANCY_KEY_H,
	DANCY_KEY_I,
	DANCY_KEY_J,
	DANCY_KEY_K,
	DANCY_KEY_L,
	DANCY_KEY_M,
	DANCY_KEY_N,
	DANCY_KEY_O,
	DANCY_KEY_P,
	DANCY_KEY_Q,
	DANCY_KEY_R,
	DANCY_KEY_S,
	DANCY_KEY_T,
	DANCY_KEY_U,
	DANCY_KEY_V,
	DANCY_KEY_W,
	DANCY_KEY_X,
	DANCY_KEY_Y,
	DANCY_KEY_Z,
	DANCY_KEY_1,
	DANCY_KEY_2,
	DANCY_KEY_3,
	DANCY_KEY_4,
	DANCY_KEY_5,
	DANCY_KEY_6,
	DANCY_KEY_7,
	DANCY_KEY_8,
	DANCY_KEY_9,
	DANCY_KEY_0,
	DANCY_KEY_ENTER,
	DANCY_KEY_ESCAPE,
	DANCY_KEY_BACKSPACE,
	DANCY_KEY_TAB,
	DANCY_KEY_SPACE,
	DANCY_KEY_UNDERSCORE,
	DANCY_KEY_EQUALS,
	DANCY_KEY_LEFTBRACKET,
	DANCY_KEY_RIGHTBRACKET,
	DANCY_KEY_BACKSLASH,
	DANCY_KEY_HASH,
	DANCY_KEY_SEMICOLON,
	DANCY_KEY_APOSTROPHE,
	DANCY_KEY_GRAVE,
	DANCY_KEY_COMMA,
	DANCY_KEY_PERIOD,
	DANCY_KEY_SLASH,
	DANCY_KEY_CAPSLOCK,
	DANCY_KEY_F1,
	DANCY_KEY_F2,
	DANCY_KEY_F3,
	DANCY_KEY_F4,
	DANCY_KEY_F5,
	DANCY_KEY_F6,
	DANCY_KEY_F7,
	DANCY_KEY_F8,
	DANCY_KEY_F9,
	DANCY_KEY_F10,
	DANCY_KEY_F11,
	DANCY_KEY_F12,
	DANCY_KEY_PRINTSCREEN,
	DANCY_KEY_SCROLLLOCK,
	DANCY_KEY_PAUSE,
	DANCY_KEY_INSERT,
	DANCY_KEY_HOME,
	DANCY_KEY_PAGEUP,
	DANCY_KEY_DELETE,
	DANCY_KEY_END,
	DANCY_KEY_PAGEDOWN,
	DANCY_KEY_RIGHTARROW,
	DANCY_KEY_LEFTARROW,
	DANCY_KEY_DOWNARROW,
	DANCY_KEY_UPARROW,
	DANCY_KEY_NUMLOCK,
	DANCY_KEY_PADSLASH,
	DANCY_KEY_PADASTERISK,
	DANCY_KEY_PADMINUS,
	DANCY_KEY_PADPLUS,
	DANCY_KEY_PADENTER,
	DANCY_KEY_PAD1,
	DANCY_KEY_PAD2,
	DANCY_KEY_PAD3,
	DANCY_KEY_PAD4,
	DANCY_KEY_PAD5,
	DANCY_KEY_PAD6,
	DANCY_KEY_PAD7,
	DANCY_KEY_PAD8,
	DANCY_KEY_PAD9,
	DANCY_KEY_PAD0,
	DANCY_KEY_PADDELETE,
	DANCY_KEY_NONUS,

	dancy_key_223 = 223,

	DANCY_KEY_LCTRL,
	DANCY_KEY_LSHIFT,
	DANCY_KEY_LALT,
	DANCY_KEY_LGUI,
	DANCY_KEY_RCTRL,
	DANCY_KEY_RSHIFT,
	DANCY_KEY_RALT,
	DANCY_KEY_RGUI,

	dancy_key_255 = 255
};

#define DANCY_KEYTYP_REPEAT     (0x00004000)
#define DANCY_KEYTYP_RELEASE    (0x00008000)

#define DANCY_KEYMOD_LCTRL      (0x00010000)
#define DANCY_KEYMOD_LSHIFT     (0x00020000)
#define DANCY_KEYMOD_LALT       (0x00040000)
#define DANCY_KEYMOD_LGUI       (0x00080000)
#define DANCY_KEYMOD_RCTRL      (0x00100000)
#define DANCY_KEYMOD_RSHIFT     (0x00200000)
#define DANCY_KEYMOD_RALT       (0x00400000)
#define DANCY_KEYMOD_RGUI       (0x00800000)

#define DANCY_KEYMOD_NUMLOCK    (0x01000000)
#define DANCY_KEYMOD_CAPSLOCK   (0x02000000)
#define DANCY_KEYMOD_SCROLLLOCK (0x04000000)

#define DANCY_KEYMOD_CTRL       (DANCY_KEYMOD_LCTRL  | DANCY_KEYMOD_RCTRL)
#define DANCY_KEYMOD_SHIFT      (DANCY_KEYMOD_LSHIFT | DANCY_KEYMOD_RSHIFT)
#define DANCY_KEYMOD_ALT        (DANCY_KEYMOD_LALT   | DANCY_KEYMOD_RALT)

#endif
