/*
 * Copyright (c) 2020 Antti Tiihala
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * dancy/palette.h
 *      Header of Dancy Operating System
 */

#ifndef DANCY_PALETTE_H
#define DANCY_PALETTE_H

#define DANCY_PALETTE_0 0x00000000
#define DANCY_PALETTE_1 0x00AA0000
#define DANCY_PALETTE_2 0x0000AA00
#define DANCY_PALETTE_3 0x00AAAA00
#define DANCY_PALETTE_4 0x000000AA
#define DANCY_PALETTE_5 0x00AA00AA
#define DANCY_PALETTE_6 0x000055AA
#define DANCY_PALETTE_7 0x00AAAAAA
#define DANCY_PALETTE_8 0x00555555
#define DANCY_PALETTE_9 0x00FF5555
#define DANCY_PALETTE_A 0x0055FF55
#define DANCY_PALETTE_B 0x00FFFF55
#define DANCY_PALETTE_C 0x005555FF
#define DANCY_PALETTE_D 0x00FF55FF
#define DANCY_PALETTE_E 0x0055FFFF
#define DANCY_PALETTE_F 0x00FFFFFF

#endif
